/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:158: RuntimeWarning: invalid value encountered in double_scalars
  mean = mean_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:164: RuntimeWarning: invalid value encountered in double_scalars
  var = var_numerator / denominator
/storage/work/s/szk381/Py_mass_radius_working/PyCode/MLE_fit.py:173: RuntimeWarning: invalid value encountered in double_scalars
  p_beta = quantile_numerator / denominator
